statefarm_microsite/config/routes.rb
StatefarmMicrosite::Application.routes.draw do
  devise_for :admins
  devise_for :users
  
  root :to => 'posts#user_view'
  match '/admin' => 'posts#index'
  resources :headings
  scope :module => "admin" do
    resources :posts
  end
  namespace :admin do
    resources :posts
  end
  

end

statefarm_microsite/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  VALID_EMAILS = %w(ddb.com ny.ddb.com)
  
protected
  def valid_email_domain(email_address)
    (email_address =~ /#{INVALID_EMAILS.map{|a| Regexp.quote(a)}.join("|")}/)
  end
end

statefarm_microsite/app/models/header2.rb
class Header2 < ActiveRecord::Base
end

statefarm_microsite/app/models/heading.rb
class Heading < ActiveRecord::Base
end

statefarm_microsite/app/models/post.rb
class Post < ActiveRecord::Base
    has_attached_file :photo,
	:styles => {
	  :tiny => "35x35",
	  :preview => "175x175",
	  :large => "300x300"
	  }
    has_attached_file :video
    has_attached_file :asset
    validates :name, :presence => true
    validates :name, :length => {:minimum => 0, :maximum => 500}
    validates :description, :presence => true
end

statefarm_microsite/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

statefarm_microsite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

statefarm_microsite/app/controllers/headings_controller.rb
class HeadingsController < ApplicationController
  # GET /headings
  # GET /headings.xml
  def index
    @headings = Heading.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @headings }
    end
  end

  # GET /headings/1
  # GET /headings/1.xml
  def show
    @heading = Heading.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @heading }
    end
  end

  # GET /headings/new
  # GET /headings/new.xml
  def new
    @heading = Heading.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @heading }
    end
  end

  # GET /headings/1/edit
  def edit
    @heading = Heading.find(params[:id])
  end

  # POST /headings
  # POST /headings.xml
  def create
    @heading = Heading.new(params[:heading])

    respond_to do |format|
      if @heading.save
        format.html { redirect_to(@heading, :notice => 'Heading was successfully created.') }
        format.xml  { render :xml => @heading, :status => :created, :location => @heading }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @heading.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /headings/1
  # PUT /headings/1.xml
  def update
    @heading = Heading.find(params[:id])

    respond_to do |format|
      if @heading.update_attributes(params[:heading])
        format.html { redirect_to(@heading, :notice => 'Heading was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @heading.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /headings/1
  # DELETE /headings/1.xml
  def destroy
    @heading = Heading.find(params[:id])
    @heading.destroy

    respond_to do |format|
      format.html { redirect_to(headings_url) }
      format.xml  { head :ok }
    end
  end
end

statefarm_microsite/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_admin!, :only => [:index, :edit, :create, :destroy]
  before_filter :authenticate_user!, :only => [:user_view]
  
 # def download
   # @post = Post.find(params[:id]).photo.url.to_s
   # send_file("#{RAILS_ROOT}/" + post.photo.url.to_s, :type => 'image/jpeg', :disposition => 'true' #attachment will be downloaded.

  #end
  
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end
  
  def user_view
   
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
  
  
end

statefarm_microsite/app/helpers/application_helper.rb
module ApplicationHelper
end

statefarm_microsite/app/helpers/headings_helper.rb
module HeadingsHelper
end

statefarm_microsite/app/helpers/posts_helper.rb
module PostsHelper
   def line_break(string)
      string.gsub("\n", '<br/>')
   end
end

statefarm_microsite/app/views/headings/_form.html.erb
<%= form_for(@heading) do |f| %>
  <% if @heading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@heading.errors.count, "error") %> prohibited this heading from being saved:</h2>

      <ul>
      <% @heading.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :visible %><br />
    <%= f.check_box :visible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

statefarm_microsite/app/views/headings/edit.html.erb
<header>
<ul id="headerText">
	
		<li class="headerTitle"><h1>EDIT HEADING</h1></li>
		
</ul>
</header>
<section>
<ul id="postArea">
<li class="postSectionBig">
<%= render 'form' %>

<%= link_to 'Show', @heading %> |
<%= link_to 'Back', headings_path %>
	
</li>	
</ul>
<!--POST SECTION END-->	
</section>

statefarm_microsite/app/views/headings/index.html.erb
<header>
<ul id="headerText">
	
		<li class="headerTitle"><h1>HEADER ADMIN</h1></li>
		
</ul>
</header>
<section>
<ul id="postArea">
<li class="postSectionMedium">
<div>
<p>Only the first header set as 'visible' will be displayed on the view page</p>
</div>

<table>
  <tr>
    <th>Title</th>
    <th>Visible</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @headings.each do |heading| %>
  <tr>
    <td><%= heading.title %></td>
    <td><%= heading.visible %></td>
    <td><%= link_to 'Show', heading %></td>
    <td><%= link_to 'Edit', edit_heading_path(heading) %></td>
    <td><%= link_to 'Delete', heading, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Admin Home', posts_path %>
<%= link_to 'New Heading', new_heading_path %>
</li>
</ul>
</section>

statefarm_microsite/app/views/headings/new.html.erb
<header>
<ul id="headerText">
	
		<li class="headerTitle"><h1>NEW HEADER</h1></li>
		
</ul>
</header>
<section>
<ul id="postArea">
<li class="postSectionBig">
<%= render 'form' %>
<%= link_to 'Back', headings_path %>
</li>
</ul>
</section>

statefarm_microsite/app/views/headings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @heading.title %>
</p>

<p>
  <b>Header2:</b>
  <%= @heading.header2 %>
</p>

<p>
  <b>Visible:</b>
  <%= @heading.visible %>
</p>


<%= link_to 'Edit', edit_heading_path(@heading) %> |
<%= link_to 'Back', headings_path %>

statefarm_microsite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>State Farm Microsite</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery.js', 'jquery_ujs.js', 'jquery.min.js', 'jquery.zclip.min.js', 'copyscript.js' %>
  

<script>
  // this allows jquery to be called along with scriptaculous and YUI without any conflicts
  // the only difference is all jquery functions should be called with $j instead of $
  // e.g. $j('#div_id').stuff instead of $('#div_id').stuff
//  var $j = jQuery.noConflict();
</script>


<%= csrf_meta_tag %>
</head>
<body>


<%= yield %>
<footer>
	<p>NO PURCHASE OR GAME PLAY NECESSARY TO ENTER OR WIN. Void in Quebec & where prohibited. Begins 12:00 a.m. CT on 7/12/10 & ends at 11:59 p.m. CT on 9/26/10.
	Must be a legal resident of the 50 U.S., DC or Canadian provinces of Alberta, New Brunswick or Ontario, 18+ at time of entrzzty to participate.
	Eligibility & other restrictions apply. <br/>Click here for Official Rules (with alternate method of entry) & complete details.</p>
	<ul id="footerBtns">
		<li><a href="http://www.statefarm.com/agent/index.xhtml" target="_blank"><%= image_tag 'find_agent_btn.jpg' %></a></li>
		<li><a href="http://www.statefarm.com" target="_blank"><%= image_tag 'download_btn.jpg' %></a></li>
	</ul>
	
	<ul id="footerNav">
		<li><a href="">Official Rules</a></li>
		<li><a href="#">Privacy Policy</a></li>
		<li><a href="#">Ask Us</a></li>
		<li><a href="#">MLB Privacy Policy</a></li>
	</ul>
</footer>
</body>
</html>

statefarm_microsite/app/views/posts/_form.html.erb
    <%= form_for(@post, :html => {:multipart => true}) do |f| %>
      <% if @post.errors.any? %>
	<div id="error_explanation">
	  <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

	  <ul>
	  <% @post.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
	  </ul>
	</div>
      <% end %>

      <div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
      </div>
    
    <div class="field">
	<%= f.label :description %><br />
	<%= f.text_area :description %>
      </div>
     
    <div class="field">
	<%= f.label 'Thumbnail Image' %><br />
	<%= f.file_field :photo %>
      </div>
    <div class="field">
	<%= f.label 'Video Link - Instructions: use "Embed" link from YouTube' %><br />
	<%= f.text_area :videolink %>
      </div>
    <div class="field">
	<%= f.label :asset %><br />
	<%= f.file_field :asset %>
      </div>


      <div class="field">
	<%= f.label :visible %><br />
	<%= f.check_box :visible %>
      </div>
      <div class="actions">
	<%= f.submit %>
      </div>
      <% end %>

statefarm_microsite/app/views/posts/edit.html.erb
<header>
<ul id="headerText">
	
		<li class="headerTitle"><h1>EDIT POST</h1></li>
		
</ul>
</header>
<section>
<ul id="postArea">
<li class="postSectionBig">
<%= render 'form' %>
</li>
</ul>
</section>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

statefarm_microsite/app/views/posts/index.html.erb
<header>
<ul id="headerText">
	
		<li class="headerTitle"><h1>ADMINISTRATION</h1></li>
		<li><p>Administer your site</p></li>
</ul>
</header>

<section>
<ul id="postArea">
<li class="postSectionBig">
		
	      <table id="indextable">
	<tr>
	  <th>Name</th>
	  <th>Description</th>
	  <th>Asset</th>
	  <th>Image</th>
	  <th>Video</th>
	  <th>Visible</th>
	  <th></th>
	  <th></th>
	  <th></th>
	</tr>

      <%= link_to 'Headers', headings_path %>

      <% @posts.each do |post| %>
	<tr>
	  <td><%= post.name %></td>
	  <td width="100"><%= post.description %></td>
	  <td><%= if post.asset? then link_to('Download', post.asset.url) end %></td>
	  <td><%= if post.photo? then link_to('Download', post.photo.url) end %></td>
	  <td><%= if post.video? then link_to('Download', post.video.url) end %></td>
	  <td><%= if admin_signed_in? 
		    post.visible 
		  end
	      %>
	  </td>
	  <td><%= link_to 'Show', post %></td>
	  <td><%= if admin_signed_in? 
		      link_to 'Edit', edit_post_path(post) 
		  end %>
	  </td>
	  <td><%= if admin_signed_in? 
		      link_to 'Delete', post, :confirm => 'Are you sure?', :method => :delete 
		  end
	      %>
	  </td>
	</tr>
      <% end %>
      </table>

      <br />

      <%= if admin_signed_in? 
	      link_to 'New Post', new_post_path 
	  end
      %>
      <!--POST 2 END-->


	
</li>	
</ul>
<!--POST SECTION END-->	
</section>

statefarm_microsite/app/views/posts/new.html.erb
<header>
<ul id="headerText">
	
		<li class="headerTitle"><h1>NEW POST</h1></li>
		
</ul>
</header>
<section>
<ul id="postArea">
<li class="postSectionBig">
<%= render 'form' %>
</li>
</ul>
</section>


<%= link_to 'Back', posts_path %>

statefarm_microsite/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<header>
<ul id="headerText">
	
		<li class="headerTitle"><h1>VIEW POST</h1></li>
		
</ul>
</header>
<section>
  <ul id="postArea">
  <li class="postSectionBig">
      <p>
	<b>Name:</b>
	<%= @post.name %>
      </p>

      <p>
	<b>Video:</b>
	<%= @post.videolink %>
      </p>
      <p>

       <p>
	<b>Description:</b>
	<%= @post.description %>
      </p>
      <p>

      <p>

      <b>Image:</b>
      <%= if @post.photo? then
	    link_to @post.photo.url , @post.photo.url 
	  end 
      %>
      </p>

      <p>

      <b>Asset:</b>
      <%= if @post.asset? then
	    link_to @post.asset.url , @post.asset.url 
	  end 
      %>
      </p>

      <p>
	<b>Visible:</b>
	<%= @post.visible %>
      </p>

      <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Posts Home', posts_path %>
    </li>
  </ul>
</section>

statefarm_microsite/app/views/posts/user_view.html.erb
<%= javascript_include_tag 'jquery.bgiframe-2.1.2.js', 'jquery.ui.core.js', 'jquery.ui.widget.js', 'jquery.ui.mouse.js', 'jquery.ui.draggable.js', 'jquery.ui.position.js', 'jquery.ui.resizable.js',
'jquery.ui.dialog.js' %>
<link rel="stylesheet" type="text/css" href="stylesheets/jquery.fancybox-1.3.4.css" media="screen" />
<%= stylesheet_link_tag 'jquery-ui-1.8.14.custom.css' %>
<link rel="stylesheet" href="stylesheets/style.css" />
<script src="javascripts/modernizr-1.7.min.js"></script>
  <link rel="shortcut icon" href="_/img/favicon.ico">
<!-- The is the icon for iOS's Web Clip. -->
	<link rel="apple-touch-icon" href="_/img/apple-touch-icon.png">
<header>
<ul id="headerText">
	
		<li class="headerTitle"><h1>CHARITY RESOURCES</h1></li>
		<li><p>Here you'll find downloadable images, videos and conversation starters to engage with your fans.</p></li>
</ul>
</header>
     
<section>
<ul id="postArea">
	<li class="postHeadline">
		<h2>
		    <%= if Heading.where(:visible => true).empty? then '' else Heading.find(:first, :conditions => ['visible = ?', true]).title.to_s end %><br/>
		    
		</h2>
	</li>
<!--POST 1 START-->
   
	
	<% @posts.each_with_index do |post, index| %>
	  <% if post.visible? %>
		    <% if post.videolink? %>
			<div id="dialog-modal<%= post.id %>" class="dialogdivs">
			  <iframe width="495" height="389" src="<%= post.videolink.to_s %>" frameborder="0" allowfullscreen></iframe>
			</div>
		     <% end %>

	      <li class="postSection<%= if index % 2 == 0 then 1.to_s else 2.to_s end %>">
		    
		    <div class="postThumb"><%= 
		    if post.photo? and not post.videolink?
			image_tag(post.photo.url, :height => '119', :width => '178')
		    elsif post.photo? and post.videolink?    
			image_tag(post.photo.url, :border=>0, :height => '119', :width => '178', :id => ('thumbnail' + post.id.to_s))
		    else
			image_tag('blank.png', :height => '119', :width => '178')
		    end
		      %></div>
		    
		    <div class="postInfo">
			    <p class="copytext" ><%= simple_format(auto_link(post.description)) %>
			    
			    </p>
			    <br/>
			    <p>Posted <%= post.created_at.strftime("%m/%d/%Y").to_s %></p>
		    </div>
		    <div class="downloadBtn">
		    <%= 
		    if post.asset?
		      link_to(image_tag('download_btn.png', :border=>0), post.asset.url.to_s)
			# puts '<br/>'
		    else
		      image_tag('blank.png', :width => '141', :height => '35')
		    end
		      %>
		    </a></div>
	      </li>
	  <% end %>
	<% end %>
<!--POST 2 END-->


	
	
</ul>
<!--POST SECTION END-->	
</section>

	<script>
	
	function videopopup() {
		// a workaround for a flaw in the demo system (http://dev.jqueryui.com/ticket/4375), ignore!
		$("#dialog:ui-dialog").dialog( "destroy" );
		
	/*
		$("#dialog-modal4").dialog({
			height: 360,
			width: 440,
			modal: true
		});
	*/	
		// prevents browser from scrolling to top on each click by forcing
		// broswer to scroll to where video is playing
		//var d = $("#dialog-modal8").position();
		//window.scrollTo( d.left , d.top);

	}

	<% @posts.each_with_index do |post, index| %>
		    <% if post.visible? %>
		      <% if post.videolink? %>
	
			    $("#thumbnail<%= post.id %>").click(function () {
			      $("#dialog-modal<%= post.id %>").dialog({
				    height: 450,
				    width: 540,
				    position: 'center',
				    modal: true
			    });
			    });
		      <% end %>
		    <% end %>
		<% end %>

	      
		//$("a").click(videopopup);
	$(document).ready(function() {
	  	$(".dialogdivs").hide();
		
	});  
	//$("a").click(videopopup())
	</script>